# Reusable workflow for all macOS builds
name: Fuse Utils For macOS
run-name: Build Fuse Utils for macOS / ${{ github.actor }} /

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      dependencies:
        type: string
        required: false
        default: ""
      configure_params:
        type: string
        required: false
        default: ""
      libspectrum_key:
        type: string
        required: false
        default: "fuse-utils"

jobs:
  build:
    name: Build Utils
    runs-on: macos-26
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
    steps:
      - name: (1) Install dependencies
        run: |
          echo "Inspect if brew installed .."
          brew doctor || true

          echo "Upgrade bash (fix |& ) .."
          brew install bash
          which -a bash
          bash --version
          sudo sh -c 'echo /opt/homebrew/bin/bash >> /etc/shells'

          echo "Installing dependencies .."
          brew install \
            automake \
            bzip2 \
            libgcrypt \
            glib \
            libtool \
            libxml2 \
            ${{ inputs.dependencies }}

          echo "Configuring Homebrew search paths .."
          echo "CPPFLAGS=-I$(brew --prefix)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix libgcrypt)/include -I$(brew --prefix glib)/include -I$(brew --prefix libxml2)/include" >> "$GITHUB_ENV"
          echo "LDFLAGS=-L$(brew --prefix)/lib -L$(brew --prefix bzip2)/lib -L$(brew --prefix libgcrypt)/lib -L$(brew --prefix glib)/lib -L$(brew --prefix libxml2)/lib" >> "$GITHUB_ENV"
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:$(brew --prefix bzip2)/lib/pkgconfig:$(brew --prefix libgcrypt)/lib/pkgconfig:$(brew --prefix glib)/lib/pkgconfig:$(brew --prefix libxml2)/lib/pkgconfig" >> "$GITHUB_ENV"

      - name: (2) Check out repository code
        uses: actions/checkout@v6

      - name: (3) Download libspectrum artefact
        uses: actions/download-artifact@v8
        with:
          name: libspectrum-installed-macos-${{ inputs.libspectrum_key }}
          path: libspectrum

      - name: (4) Install libspectrum from artefact
        run: |
          # Extract (-x) files into /usr/local
          sudo tar --directory / -xvf libspectrum/libspectrum-installed-macos.tar
          echo "Done"

      - name: (5) Autogen.sh
        run: ./autogen.sh

      - name: (6) Configure for macOS
        run: |
          ./configure ${{ inputs.configure_params }} \
          |& tee ./configure.out

      - name: (7) Verify output from configure
        # Most of the tested strings are common for all macOS builds
        run: |          
          .github/scripts/in_config.sh "The Fuse utils are ready to be compiled"
          .github/scripts/in_config.sh "zlib support: yes"
          .github/scripts/in_config.sh "libjpeg support: yes"
          .github/scripts/in_config.sh "libpng support: yes"
          .github/scripts/in_config.sh "libgcrypt support: yes"
          .github/scripts/in_config.sh "libspectrum's internal GLib replacement: no"

      - name: (8) Make
        run: make

      - name: (9) Install
        run: sudo make install

      - name: (10) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
