name: Fuse Utils For Linux
run-name: Build Fuse Utils for Linux / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]

jobs:
  libspectrum:
    # Build libspectrum locally (all libs enabled, real glib)
    name: "Libspectrum lib (Linux)"
    uses: ./.github/workflows/build_libspectrum_linux_sub.yml
    with:
      key: fuse-utils


#########################################
### SUPPORTED Linux configurations ###
#########################################

  # Default build without any configure params
  utils-default:
    name: "Fuse Utils Default (Linux)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: Default
      dependencies: "libaudiofile-dev libgcrypt-dev libglib2.0-dev libjpeg-dev libpng-dev zlib1g-dev"
      configure_params: ""
